### ISSUE TITLE
关于【BlockScout 开源浏览器安装部署指南】文章请教

### ISSUE THREAD

**Issue by 0xhhhhh** [holechain/holechain.github.io#2]
文章地址：https://mhxw.life/2021-10-05-blockscout-deployment-guide/

我用Docker的方式部署，在启动的时候连接https://infura.io/给的ETH http、ws API地址就可以正常运行，如果链接我本地部署的私有网络就会报错

```
Retrying.
2021-12-22T04:44:21.095 application=indexer fetcher=block_catchup first_block_number=155 last_block_number=146 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 10, 13, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 49, 55, 46, 50, 133, 108, 105, 110, 117, 120>>
    (indexer 0.1.0) lib/indexer/transform/blocks.ex:78: Indexer.Transform.Blocks.recover_pub_key/2
    (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

本地运行三个节点，连接其中的任何一个都不行，所以想问下大佬知道这这方面应该是哪里的问题吗

**Comment by mhxw** [comment]
不好意思，现在才看到你的消息。如果你仍然感兴趣，可以参考 Blockscout 的文档进行部署。文档内容已经非常详细，而且代码也发生了不少变更，建议根据最新版本的文档操作哈。
